# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               UpBeat
tagline:             'videos'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://up-beat.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              UpBeat
  url:               https://up-beat.github.io
  email:             up@

# Custom vars
version:             1.0.0

github:
  repo:               up-beat/up-beat.github.io
  branch:             master
